### ISSUE TITLE
Coping AtlaClient source code to Atlantis main repo

### ISSUE THREAD

**Issue by artyomtrityak** [AtlaClient/AtlaClient#1]
Hi,

I want to consolidate all Atlantis game clients into main Atlantis Pbem github org, is it okay if i will copy source code there?

Thanks,
Artem
http://atlantis-pbem.com/

**Comment by pradd** [comment]
Sure, go ahead.

**Comment by artyomtrityak** [comment]
Do they both (-old and this one) compile and work?

**Comment by pradd** [comment]
Unfortunately... ;( 
I didn't manage to assemble an environment resembling the author's one, too many years have passed; and my c++ skills are not enough to migrate the code to a newer version of Borland.
So the code is here waiting for an expert or an industrial archeology fan.
